---
- name: OpenShift Container Platform 4.3+ Post Deployment Cluster Configuration
  gather_facts: no
  hosts: localhost
  become: false

  roles:
  - common
    # confirms that inventory matches cluter actually logged into.
  - infrastructure
    # applies
    #   - ingress_controller
    #   - internal_registry
    #   - cluster_monitoring
    #   - cluster_logging
  - network_policy
    # creates network policy objects and updates the new project request template
