  - name: Registry infrastructure node selection and taint toleration
    k8s:
      state: present
      api_version: imageregistry.operator.openshift.io/v1
      definition:
        kind: Config
        metadata:
          name: cluster
        spec:
          nodeSelector:
            node-role.kubernetes.io/infra: ""
          tolerations:
            - effect: NoSchedule
              key: infra
              value: reserved
            - effect: NoExecute
              key: infra
              value: reserved
